{
 "title": "TP1 OpenTelemetry",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {
     "query": "label_values(otel_http_server_duration_milliseconds_bucket, exported_job)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(otel_http_server_duration_milliseconds_bucket, http_route)"
    }
   },
   {
    "name": "rateinterval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "predictive_interval", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "predictive_offset", "query": "1h,2h,6h,12h,1d,2d,3d,1w" }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per service during selected time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(otel_http_server_duration_milliseconds_count{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_route) (increase(otel_http_server_duration_milliseconds_sum{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$__range])) / sum by(http_route)(increase(otel_http_server_duration_milliseconds_count{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(otel_http_server_duration_milliseconds_bucket[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route)(increase(otel_http_server_duration_milliseconds_count[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route) (otel_http_server_duration_milliseconds_count{http_status_code=~\"2.*\"}) / sum by(http_route) (otel_http_server_duration_milliseconds_count)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS per endpoint over last $rateinterval, $predictive_interval prediction range, $predictive_offset prediction offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(otel_http_server_duration_milliseconds_count{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$rateinterval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(route) (\r\n  rate(\r\n    otel_http_server_duration_milliseconds_count{\r\n      http_route=~\"$http_route\",\r\n      exported_job=\"$service_name\"\r\n    }[$rateinterval]\r\n  )\r\n)",
     "legendFormat": "predictive threshold"
    }
   ]
  },
  {
   "title": "P95 per endpoint over $rateinterval interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(otel_http_server_duration_milliseconds_bucket{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$rateinterval])) by(http_route, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 over selected time range",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(otel_http_server_duration_milliseconds_bucket{exported_job=\"$service_name\",http_route=~\"$http_route\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "filters": [
      { "id": "1f361689", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{ resource.service.name = \"$service_name\"}",
     "serviceMapQuery": "{}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (\r\n  increase(\r\n    otel_http_server_duration_milliseconds_bucket{\r\n      http_route=\"$http_route\",\r\n      exported_job=\"$service_name\",\r\n    }[$__range]\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Log of All Microservices",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"auth-service|user-service|problems-service\"} |\r\nline_format `{{if .severity_text}}{{.severity_text}}{{else}}UNK{{end}} [{{.service_name}}] {{if .component}}{{.component}}{{end}} {{__line__}} {{if .trace_id}}[{{.trace_id}}]{{end}}`",
     "maxLines": 80
    }
   ]
  }
 ]
}